# Generated by Django 2.0.7 on 2018-09-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='기사 제목')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('rank', models.CharField(max_length=10, verbose_name='기사 랭크 순위')),
                ('content', models.TextField(verbose_name='기사 내용')),
                ('content_html', models.TextField(verbose_name='기사 내용 코드')),
                ('url', models.TextField(verbose_name='원문 링크')),
                ('date', models.CharField(max_length=30, verbose_name='')),
            ],
        ),
    ]
